/**
 * Match Threads — live game discussion threads on Hive.
 *
 * Each match gets a container post under @sportsbites (same account as daily
 * sportsbites). Users post 280-char sportsbites as replies to the match
 * container. Threads are auto-created from ESPN events and remain
 * open for 24 hours after the event ends.
 */

import { SportsEvent, MatchThread } from '@/types/sports';
import {
  SPORTS_ARENA_CONFIG,
  MUTED_AUTHORS,
  SPORTSBITES_CONFIG,
  MATCH_THREAD_CONFIG,
  getMatchThreadPermlink,
  createMatchThreadSportsbiteOperation,
} from './shared';
import { makeHiveApiCall } from './api';
import { transformToSportsbite, Sportsbite } from './sportsbites';
import { error as logError } from './logger';

// Re-export from shared for backward compatibility
export { MATCH_THREAD_CONFIG, getMatchThreadPermlink, createMatchThreadSportsbiteOperation };

// ---------------------------------------------------------------------------
// Thread status
// ---------------------------------------------------------------------------

/** Returns true if the thread is still open for posting. */
export function isThreadOpen(
  eventDate: string,
  eventStatus: SportsEvent['status'],
  endDate?: string
): boolean {
  if (eventStatus === 'live' || eventStatus === 'upcoming') return true;

  // For finished events, allow posting for THREAD_OPEN_HOURS after the event ends.
  // Use endDate for multi-day events (e.g. golf tournaments), otherwise fall back to start date.
  const referenceTime = new Date(endDate || eventDate).getTime();
  const now = Date.now();
  const hoursSinceEnd = (now - referenceTime) / (1000 * 60 * 60);
  return hoursSinceEnd <= MATCH_THREAD_CONFIG.THREAD_OPEN_HOURS;
}

// ---------------------------------------------------------------------------
// Container post builders
// ---------------------------------------------------------------------------

export function buildMatchThreadBody(event: SportsEvent): string {
  const teams = event.teams ? `**${event.teams.home}** vs **${event.teams.away}**` : event.name;

  const lines = [
    `## Match Thread: ${teams}`,
    '',
    `${event.icon} ${event.sport}${event.league ? ` - ${event.league}` : ''}`,
    event.venue ? `Venue: ${event.venue}` : null,
    `Kickoff: ${new Date(event.date).toUTCString()}`,
    '',
    'Share your live reactions, predictions, and hot takes!',
    '',
    '---',
    `*Auto-generated by [Sportsblock](https://sportsblock.app)*`,
  ];

  return lines.filter((l) => l !== null).join('\n');
}

export function buildMatchThreadMetadata(event: SportsEvent): string {
  return JSON.stringify({
    app: `${SPORTS_ARENA_CONFIG.APP_NAME}/${SPORTS_ARENA_CONFIG.APP_VERSION}`,
    format: 'markdown',
    tags: MATCH_THREAD_CONFIG.DEFAULT_TAGS,
    community: SPORTSBITES_CONFIG.COMMUNITY_ID,
    content_type: MATCH_THREAD_CONFIG.CONTENT_TYPE,
    match_thread: {
      event_id: event.id,
      sport: event.sport,
      league: event.league,
      home_team: event.teams?.home,
      away_team: event.teams?.away,
      venue: event.venue,
      kickoff: event.date,
    },
  });
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/** Build a MatchThread object from an event, bite count, and live-event set. */
export function createMatchThread(
  event: SportsEvent,
  biteCount: number,
  liveEventIds: Set<string>
): MatchThread {
  return {
    eventId: event.id,
    permlink: getMatchThreadPermlink(event.id),
    event,
    biteCount,
    isOpen: isThreadOpen(event.date, event.status, event.endDate),
    isLive: liveEventIds.has(event.id) || event.status === 'live',
  };
}

// ---------------------------------------------------------------------------
// Hive duplicate error detection
// ---------------------------------------------------------------------------

/** Returns true if a Hive broadcast error indicates the content already exists. */
export function isHiveDuplicateError(error?: string): boolean {
  return (
    !!error &&
    (error.includes('already') || error.includes('duplicate') || error.includes('permlink'))
  );
}

// ---------------------------------------------------------------------------
// Fetch match thread bites from Hive
// ---------------------------------------------------------------------------

export async function fetchMatchThreadBites(eventId: string): Promise<Sportsbite[]> {
  try {
    const permlink = getMatchThreadPermlink(eventId);

    const replies = await makeHiveApiCall<unknown[]>('condenser_api', 'get_content_replies', [
      MATCH_THREAD_CONFIG.PARENT_AUTHOR,
      permlink,
    ]);

    if (!Array.isArray(replies)) {
      return [];
    }

    return replies
      .map(transformToSportsbite)
      .filter((s): s is Sportsbite => s !== null)
      .filter((s) => !MUTED_AUTHORS.includes(s.author));
  } catch (error) {
    logError(
      `Error fetching match thread bites for event ${eventId}`,
      'fetchMatchThreadBites',
      error instanceof Error ? error : undefined
    );
    throw error;
  }
}
