import type { BadgeDefinition, RankTier } from './types';

export const BADGE_CATALOGUE: BadgeDefinition[] = [
  // ── Content ──────────────────────────────────────────────
  {
    id: 'first-post',
    name: 'First Post',
    description: 'Published your first piece of sports content on SportsBlock.',
    category: 'content',
    imageSrc: '/badges/achievement/first-post.png',
    shape: 'circle',
    color: '#00C49A',
    glow: false,
    metric: 'totalPosts',
    threshold: 1,
    triggers: ['post_created'],
  },
  {
    id: 'prolific-writer',
    name: '10 Posts',
    description: "Published 10 posts. You're building a voice.",
    category: 'content',
    imageSrc: '/badges/achievement/10-posts.png',
    shape: 'circle',
    color: '#00C49A',
    glow: false,
    metric: 'totalPosts',
    threshold: 10,
    triggers: ['post_created'],
  },
  {
    id: 'content-machine',
    name: '50 Posts',
    description: 'Published 50 posts. A real contributor to the community.',
    category: 'content',
    imageSrc: '/badges/achievement/50-posts.png',
    shape: 'circle',
    color: '#00E5B4',
    glow: false,
    metric: 'totalPosts',
    threshold: 50,
    triggers: [],
  },
  {
    id: 'first-bite',
    name: 'First Bite',
    description: 'Posted your first sportsbite',
    category: 'content',
    shape: 'circle',
    color: '#00C49A',
    glow: false,
    metric: 'totalSportsbites',
    threshold: 1,
    triggers: ['sportsbite_created'],
  },
  {
    id: 'bite-master',
    name: '100 Bites',
    description: '100 Sportsbites published. Always ready with the hot take.',
    category: 'content',
    imageSrc: '/badges/achievement/100-bites.png',
    shape: 'circle',
    color: '#00E5B4',
    glow: false,
    metric: 'totalSportsbites',
    threshold: 100,
    triggers: [],
  },
  {
    id: '500-bites',
    name: '500 Bites',
    description: '500 Sportsbites. The king of the quick take.',
    category: 'content',
    imageSrc: '/badges/achievement/500-bites.png',
    shape: 'circle',
    color: '#E8A020',
    glow: true,
    metric: 'totalSportsbites',
    threshold: 500,
    triggers: [],
  },

  // ── Engagement ───────────────────────────────────────────
  {
    id: 'first-comment',
    name: 'First Comment',
    description: 'Left your first comment',
    category: 'engagement',
    shape: 'circle',
    color: '#00C49A',
    glow: false,
    metric: 'totalComments',
    threshold: 1,
    triggers: ['comment_created'],
  },
  {
    id: 'conversationalist',
    name: '1K Comments',
    description: '1,000 comments made. The backbone of the community.',
    category: 'engagement',
    imageSrc: '/badges/achievement/1k-comments.png',
    shape: 'circle',
    color: '#00C49A',
    glow: false,
    metric: 'totalComments',
    threshold: 1000,
    triggers: [],
  },
  {
    id: 'crowd-pleaser',
    name: 'Crowd Pleaser',
    description: 'Your content has been viewed 100 times',
    category: 'engagement',
    shape: 'circle',
    color: '#00C49A',
    glow: false,
    metric: 'totalViewsReceived',
    threshold: 100,
    triggers: [],
  },
  {
    id: 'viral',
    name: '10K Views',
    description: "10,000 external views on your content. You're getting noticed.",
    category: 'engagement',
    imageSrc: '/badges/achievement/10k-views.png',
    shape: 'circle',
    color: '#E84040',
    glow: false,
    metric: 'totalViewsReceived',
    threshold: 10000,
    triggers: [],
  },
  {
    id: 'first-tip',
    name: 'First Tip',
    description: 'Received your first tip from a fellow fan. Your content has value.',
    category: 'engagement',
    imageSrc: '/badges/achievement/first-tip.png',
    shape: 'circle',
    color: '#00C49A',
    glow: false,
    metric: 'totalTipsReceived',
    threshold: 1,
    triggers: [],
  },

  // ── Predictions ──────────────────────────────────────────
  {
    id: 'first-prediction',
    name: 'First Prediction',
    description: 'Placed your first prediction stake',
    category: 'predictions',
    shape: 'diamond',
    color: '#00C49A',
    glow: false,
    metric: 'predictions.total',
    threshold: 1,
    triggers: ['prediction_settled'],
  },
  {
    id: 'sharp-shooter',
    name: 'Expert Predictor',
    description: '60%+ prediction win rate (min 10 predictions)',
    category: 'predictions',
    imageSrc: '/badges/achievement/expert-predictor.png',
    shape: 'diamond',
    color: '#00C49A',
    glow: false,
    metric: 'predictions.winRate',
    threshold: 0.6,
    minSample: 10,
    triggers: [],
  },
  {
    id: 'sharpshooter',
    name: 'Sharpshooter',
    description: '80%+ accuracy over 50+ predictions. Elite-level prediction.',
    category: 'predictions',
    imageSrc: '/badges/achievement/sharpshooter.png',
    shape: 'diamond',
    color: '#E8A020',
    glow: true,
    metric: 'predictions.winRate',
    threshold: 0.8,
    minSample: 50,
    triggers: [],
  },
  {
    id: 'oracle',
    name: 'The Oracle',
    description: '10 correct predictions in a row',
    category: 'predictions',
    imageSrc: '/badges/achievement/10-streak.png',
    shape: 'star',
    color: '#E8A020',
    glow: true,
    metric: 'predictions.bestStreak',
    threshold: 10,
    triggers: [],
  },
  {
    id: 'on-fire',
    name: 'On Fire',
    description: '20 consecutive correct predictions. Unstoppable.',
    category: 'predictions',
    imageSrc: '/badges/achievement/on-fire.png',
    shape: 'star',
    color: '#F5A020',
    glow: true,
    metric: 'predictions.bestStreak',
    threshold: 20,
    triggers: [],
  },
  {
    id: 'epic-caller',
    name: 'Epic Caller',
    description: '5+ correct scoreline predictions. Forensic accuracy.',
    category: 'predictions',
    imageSrc: '/badges/achievement/epic-caller.png',
    shape: 'star',
    color: '#00E5B4',
    glow: true,
    metric: 'predictions.correctScorelines',
    threshold: 5,
    triggers: [],
  },

  // ── Streaks ──────────────────────────────────────────────
  {
    id: 'streak-3',
    name: 'On Fire',
    description: '3-week posting streak',
    category: 'streak',
    shape: 'circle',
    color: '#E8A020',
    glow: false,
    metric: 'currentPostingStreak',
    threshold: 3,
    triggers: ['streak_updated'],
  },
  {
    id: 'streak-10',
    name: 'Unstoppable',
    description: '10-week posting streak',
    category: 'streak',
    shape: 'circle',
    color: '#F5A020',
    glow: true,
    metric: 'currentPostingStreak',
    threshold: 10,
    triggers: [],
  },
  {
    id: 'streak-26',
    name: 'Half Year Hero',
    description: '26-week posting streak (half a year!)',
    category: 'streak',
    shape: 'star',
    color: '#E8A020',
    glow: true,
    metric: 'longestPostingStreak',
    threshold: 26,
    triggers: [],
  },

  // ── Milestones ───────────────────────────────────────────
  {
    id: 'og-member',
    name: 'OG Member',
    description: 'Active member for 6 months',
    category: 'milestone',
    shape: 'shield',
    color: '#00C49A',
    glow: false,
    metric: 'tenure_months',
    threshold: 6,
    triggers: [],
  },
  {
    id: 'veteran',
    name: 'Veteran',
    description: 'Active member for 1 year',
    category: 'milestone',
    shape: 'shield',
    color: '#E8A020',
    glow: true,
    metric: 'tenure_months',
    threshold: 12,
    triggers: [],
  },
  {
    id: 'top-earner',
    name: 'Top Earner',
    description: 'Earned 1,000+ MEDALS lifetime',
    category: 'milestone',
    shape: 'shield',
    color: '#00E5B4',
    glow: false,
    metric: 'totalMedalsEarned',
    threshold: 1000,
    triggers: [],
  },
];

export const RANK_TIERS: RankTier[] = [
  {
    rank: 'hall-of-fame',
    label: 'Hall of Fame',
    min: 91,
    max: 100,
    bgGradient: 'bg-gradient-to-r from-yellow-400 via-amber-500 to-yellow-600',
    textColor: 'text-yellow-900',
    icon: 'Trophy',
  },
  {
    rank: 'legend',
    label: 'Legend',
    min: 76,
    max: 90,
    bgGradient: 'bg-gradient-to-r from-purple-500 via-violet-500 to-indigo-500',
    textColor: 'text-white',
    icon: 'Crown',
  },
  {
    rank: 'pundit',
    label: 'Pundit',
    min: 56,
    max: 75,
    bgGradient: 'bg-gradient-to-r from-emerald-500 to-green-600',
    textColor: 'text-white',
    icon: 'Award',
  },
  {
    rank: 'analyst',
    label: 'Analyst',
    min: 36,
    max: 55,
    bgGradient: 'bg-gradient-to-r from-cyan-500 to-teal-500',
    textColor: 'text-white',
    icon: 'BarChart3',
  },
  {
    rank: 'contender',
    label: 'Contender',
    min: 16,
    max: 35,
    bgGradient: 'bg-gradient-to-r from-blue-500 to-sky-500',
    textColor: 'text-white',
    icon: 'Swords',
  },
  {
    rank: 'rookie',
    label: 'Rookie',
    min: 0,
    max: 15,
    bgGradient: 'bg-gradient-to-r from-slate-400 to-gray-500',
    textColor: 'text-white',
    icon: 'User',
  },
];

/** Look up rank tier for a given score */
export function getRankTierForScore(score: number): RankTier {
  return (
    RANK_TIERS.find((t) => score >= t.min && score <= t.max) ?? RANK_TIERS[RANK_TIERS.length - 1]
  );
}

/** Look up badge definition by ID */
export function getBadgeById(badgeId: string): BadgeDefinition | undefined {
  return BADGE_CATALOGUE.find((b) => b.id === badgeId);
}
