import type { BadgeDefinition, RankTier } from './types';

export const BADGE_CATALOGUE: BadgeDefinition[] = [
  // ── Content ──────────────────────────────────────────────
  {
    id: 'first-post',
    name: 'First Post',
    description: 'Published your first article',
    category: 'content',
    icon: 'PenLine',
    bgGradient: 'bg-gradient-to-r from-sky-500 to-blue-500',
    textColor: 'text-white',
    glowColor: 'shadow-sky-500/30',
    metric: 'totalPosts',
    threshold: 1,
    triggers: ['post_created'],
  },
  {
    id: 'prolific-writer',
    name: 'Prolific Writer',
    description: 'Published 10 articles',
    category: 'content',
    icon: 'BookOpen',
    bgGradient: 'bg-gradient-to-r from-blue-500 to-indigo-500',
    textColor: 'text-white',
    glowColor: 'shadow-blue-500/30',
    metric: 'totalPosts',
    threshold: 10,
    triggers: ['post_created'],
  },
  {
    id: 'content-machine',
    name: 'Content Machine',
    description: 'Published 50 articles',
    category: 'content',
    icon: 'Newspaper',
    bgGradient: 'bg-gradient-to-r from-indigo-600 to-purple-600',
    textColor: 'text-white',
    glowColor: 'shadow-indigo-500/40',
    metric: 'totalPosts',
    threshold: 50,
    triggers: [],
  },
  {
    id: 'first-bite',
    name: 'First Bite',
    description: 'Posted your first sportsbite',
    category: 'content',
    icon: 'Zap',
    bgGradient: 'bg-gradient-to-r from-orange-400 to-amber-500',
    textColor: 'text-white',
    glowColor: 'shadow-orange-500/30',
    metric: 'totalSportsbites',
    threshold: 1,
    triggers: ['sportsbite_created'],
  },
  {
    id: 'bite-master',
    name: 'Bite Master',
    description: 'Posted 50 sportsbites',
    category: 'content',
    icon: 'Flame',
    bgGradient: 'bg-gradient-to-r from-red-500 to-orange-500',
    textColor: 'text-white',
    glowColor: 'shadow-red-500/40',
    metric: 'totalSportsbites',
    threshold: 50,
    triggers: [],
  },

  // ── Engagement ───────────────────────────────────────────
  {
    id: 'first-comment',
    name: 'First Comment',
    description: 'Left your first comment',
    category: 'engagement',
    icon: 'MessageSquare',
    bgGradient: 'bg-gradient-to-r from-emerald-400 to-green-500',
    textColor: 'text-white',
    glowColor: 'shadow-emerald-500/30',
    metric: 'totalComments',
    threshold: 1,
    triggers: ['comment_created'],
  },
  {
    id: 'conversationalist',
    name: 'Conversationalist',
    description: 'Left 50 comments',
    category: 'engagement',
    icon: 'MessagesSquare',
    bgGradient: 'bg-gradient-to-r from-green-500 to-teal-500',
    textColor: 'text-white',
    glowColor: 'shadow-green-500/40',
    metric: 'totalComments',
    threshold: 50,
    triggers: [],
  },
  {
    id: 'crowd-pleaser',
    name: 'Crowd Pleaser',
    description: 'Your content has been viewed 100 times',
    category: 'engagement',
    icon: 'Users',
    bgGradient: 'bg-gradient-to-r from-pink-400 to-rose-500',
    textColor: 'text-white',
    glowColor: 'shadow-pink-500/30',
    metric: 'totalViewsReceived',
    threshold: 100,
    triggers: [],
  },
  {
    id: 'viral',
    name: 'Gone Viral',
    description: 'Your content has been viewed 1,000 times',
    category: 'engagement',
    icon: 'TrendingUp',
    bgGradient: 'bg-gradient-to-r from-rose-500 to-red-600',
    textColor: 'text-white',
    glowColor: 'shadow-rose-500/40',
    metric: 'totalViewsReceived',
    threshold: 1000,
    triggers: [],
  },

  // ── Predictions ──────────────────────────────────────────
  {
    id: 'first-prediction',
    name: 'First Prediction',
    description: 'Placed your first prediction stake',
    category: 'predictions',
    icon: 'Target',
    bgGradient: 'bg-gradient-to-r from-violet-500 to-purple-500',
    textColor: 'text-white',
    glowColor: 'shadow-violet-500/30',
    metric: 'predictions.total',
    threshold: 1,
    triggers: ['prediction_settled'],
  },
  {
    id: 'sharp-shooter',
    name: 'Sharp Shooter',
    description: '60%+ prediction win rate (min 10 predictions)',
    category: 'predictions',
    icon: 'Crosshair',
    bgGradient: 'bg-gradient-to-r from-purple-500 to-fuchsia-500',
    textColor: 'text-white',
    glowColor: 'shadow-purple-500/40',
    metric: 'predictions.winRate',
    threshold: 0.6,
    minSample: 10,
    triggers: [],
  },
  {
    id: 'oracle',
    name: 'The Oracle',
    description: '10 correct predictions in a row',
    category: 'predictions',
    icon: 'Eye',
    bgGradient: 'bg-gradient-to-r from-fuchsia-600 to-pink-600',
    textColor: 'text-white',
    glowColor: 'shadow-fuchsia-500/50',
    metric: 'predictions.bestStreak',
    threshold: 10,
    triggers: [],
  },

  // ── Streaks ──────────────────────────────────────────────
  {
    id: 'streak-3',
    name: 'On Fire',
    description: '3-week posting streak',
    category: 'streak',
    icon: 'Flame',
    bgGradient: 'bg-gradient-to-r from-amber-500 to-orange-500',
    textColor: 'text-white',
    glowColor: 'shadow-amber-500/30',
    metric: 'currentPostingStreak',
    threshold: 3,
    triggers: ['streak_updated'],
  },
  {
    id: 'streak-10',
    name: 'Unstoppable',
    description: '10-week posting streak',
    category: 'streak',
    icon: 'Zap',
    bgGradient: 'bg-gradient-to-r from-orange-500 to-red-500',
    textColor: 'text-white',
    glowColor: 'shadow-orange-500/40',
    metric: 'currentPostingStreak',
    threshold: 10,
    triggers: [],
  },
  {
    id: 'streak-26',
    name: 'Half Year Hero',
    description: '26-week posting streak (half a year!)',
    category: 'streak',
    icon: 'Trophy',
    bgGradient: 'bg-gradient-to-r from-yellow-500 via-amber-500 to-orange-500',
    textColor: 'text-white',
    glowColor: 'shadow-yellow-500/50',
    metric: 'longestPostingStreak',
    threshold: 26,
    triggers: [],
  },

  // ── Milestones ───────────────────────────────────────────
  {
    id: 'og-member',
    name: 'OG Member',
    description: 'Active member for 6 months',
    category: 'milestone',
    icon: 'Clock',
    bgGradient: 'bg-gradient-to-r from-slate-500 to-zinc-500',
    textColor: 'text-white',
    glowColor: 'shadow-slate-500/30',
    metric: 'tenure_months',
    threshold: 6,
    triggers: [],
  },
  {
    id: 'veteran',
    name: 'Veteran',
    description: 'Active member for 1 year',
    category: 'milestone',
    icon: 'Shield',
    bgGradient: 'bg-gradient-to-r from-zinc-600 to-slate-700',
    textColor: 'text-white',
    glowColor: 'shadow-zinc-500/40',
    metric: 'tenure_months',
    threshold: 12,
    triggers: [],
  },
  {
    id: 'top-earner',
    name: 'Top Earner',
    description: 'Earned 1,000+ MEDALS lifetime',
    category: 'milestone',
    icon: 'Gem',
    bgGradient: 'bg-gradient-to-r from-emerald-500 to-teal-600',
    textColor: 'text-white',
    glowColor: 'shadow-emerald-500/40',
    metric: 'totalMedalsEarned',
    threshold: 1000,
    triggers: [],
  },
];

export const RANK_TIERS: RankTier[] = [
  {
    rank: 'hall-of-fame',
    label: 'Hall of Fame',
    min: 91,
    max: 100,
    bgGradient: 'bg-gradient-to-r from-yellow-400 via-amber-500 to-yellow-600',
    textColor: 'text-yellow-900',
    icon: 'Trophy',
  },
  {
    rank: 'legend',
    label: 'Legend',
    min: 76,
    max: 90,
    bgGradient: 'bg-gradient-to-r from-purple-500 via-violet-500 to-indigo-500',
    textColor: 'text-white',
    icon: 'Crown',
  },
  {
    rank: 'pundit',
    label: 'Pundit',
    min: 56,
    max: 75,
    bgGradient: 'bg-gradient-to-r from-emerald-500 to-green-600',
    textColor: 'text-white',
    icon: 'Award',
  },
  {
    rank: 'analyst',
    label: 'Analyst',
    min: 36,
    max: 55,
    bgGradient: 'bg-gradient-to-r from-cyan-500 to-teal-500',
    textColor: 'text-white',
    icon: 'BarChart3',
  },
  {
    rank: 'contender',
    label: 'Contender',
    min: 16,
    max: 35,
    bgGradient: 'bg-gradient-to-r from-blue-500 to-sky-500',
    textColor: 'text-white',
    icon: 'Swords',
  },
  {
    rank: 'rookie',
    label: 'Rookie',
    min: 0,
    max: 15,
    bgGradient: 'bg-gradient-to-r from-slate-400 to-gray-500',
    textColor: 'text-white',
    icon: 'User',
  },
];

/** Look up rank tier for a given score */
export function getRankTierForScore(score: number): RankTier {
  return (
    RANK_TIERS.find((t) => score >= t.min && score <= t.max) ?? RANK_TIERS[RANK_TIERS.length - 1]
  );
}

/** Look up badge definition by ID */
export function getBadgeById(badgeId: string): BadgeDefinition | undefined {
  return BADGE_CATALOGUE.find((b) => b.id === badgeId);
}
