import { NextResponse } from 'next/server';
import { broadcastWithKey } from '@/lib/hive-workerbee/broadcast';
import {
  getContainerPermlink,
  formatContainerDate,
  SPORTSBITES_CONFIG,
} from '@/lib/hive-workerbee/sportsbites';
import { SPORTS_ARENA_CONFIG } from '@/lib/hive-workerbee/client';
import { makeHiveApiCall } from '@/lib/hive-workerbee/api';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * Ensures today's sportsbites container exists on Hive.
 *
 * Called by the client before publishing a sportsbite. If the daily
 * container hasn't been created yet (e.g. cron hasn't fired), this
 * endpoint creates it on-demand using the server-side posting key.
 */
export async function POST() {
  const postingKey = process.env.SPORTSBITES_POSTING_KEY;
  if (!postingKey) {
    return NextResponse.json(
      { success: false, error: 'Sportsbites posting key not configured' },
      { status: 503 }
    );
  }

  try {
    const today = new Date();
    const permlink = getContainerPermlink(today);

    // Check if container already exists
    const existing = await makeHiveApiCall<Record<string, unknown>>(
      'condenser_api',
      'get_content',
      [SPORTSBITES_CONFIG.PARENT_AUTHOR, permlink]
    );

    if (existing && existing.author && (existing.body as string)?.length > 0) {
      return NextResponse.json({
        success: true,
        permlink,
        alreadyExists: true,
      });
    }

    // Container doesn't exist — create it
    const title = `Sportsbites Daily Thread - ${formatContainerDate(today)}`;
    const dateStr = today.toISOString().split('T')[0];
    const body = [
      `## Sportsbites Daily Thread - ${formatContainerDate(today)}`,
      '',
      'Share your quick sports takes! 280 characters of pure sports passion.',
      '',
      '---',
      `*Auto-generated by [Sportsblock](https://sportsblock.app) on ${dateStr}*`,
    ].join('\n');

    const metadata = JSON.stringify({
      app: `${SPORTS_ARENA_CONFIG.APP_NAME}/${SPORTS_ARENA_CONFIG.APP_VERSION}`,
      format: 'markdown',
      tags: ['sportsblock', 'sportsbites', SPORTSBITES_CONFIG.COMMUNITY_ID],
      community: SPORTSBITES_CONFIG.COMMUNITY_ID,
      content_type: 'sportsbites-container',
    });

    const result = await broadcastWithKey(
      [
        [
          'comment',
          {
            parent_author: '',
            parent_permlink: SPORTSBITES_CONFIG.COMMUNITY_ID,
            author: SPORTSBITES_CONFIG.PARENT_AUTHOR,
            permlink,
            title,
            body,
            json_metadata: metadata,
          },
        ],
      ],
      postingKey
    );

    if (!result.success) {
      throw new Error(result.error || 'Failed to create container');
    }

    console.log(`[EnsureContainer] Created container for ${dateStr}: tx=${result.transactionId}`);

    return NextResponse.json({
      success: true,
      permlink,
      created: true,
      transactionId: result.transactionId,
    });
  } catch (error) {
    console.error('[EnsureContainer] Failed:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to ensure container',
      },
      { status: 500 }
    );
  }
}
