import { NextResponse } from 'next/server';
import { createRequestContext } from '@/lib/api/response';
import { broadcastWithKey } from '@/lib/hive-workerbee/broadcast';
import {
  getContainerPermlink,
  formatContainerDate,
  SPORTSBITES_CONFIG,
} from '@/lib/hive-workerbee/sportsbites';
import { SPORTS_ARENA_CONFIG } from '@/lib/hive-workerbee/client';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const ROUTE = '/api/hive/sportsbites/ensure-container';

// In-memory cache of known-created container permlinks for this process.
// Avoids redundant broadcasts within the same server lifecycle.
const createdContainers = new Set<string>();

/**
 * Ensures today's sportsbites container exists on Hive.
 *
 * Strategy: attempt to create the container directly. If it already
 * exists, Hive returns a "duplicate" error which we treat as success.
 * This avoids a fragile pre-check via get_content.
 */
export async function POST() {
  const postingKey = process.env.SPORTSBITES_POSTING_KEY;
  if (!postingKey) {
    return NextResponse.json(
      { success: false, error: 'Sportsbites posting key not configured' },
      { status: 503 }
    );
  }

  const ctx = createRequestContext(ROUTE);
  try {
    const today = new Date();
    const permlink = getContainerPermlink(today);

    // Fast path: we already created this container in this server process
    if (createdContainers.has(permlink)) {
      return NextResponse.json({
        success: true,
        permlink,
        alreadyExists: true,
      });
    }

    const title = `Sportsbites Daily Thread - ${formatContainerDate(today)}`;
    const dateStr = today.toISOString().split('T')[0];
    const body = [
      `## Sportsbites Daily Thread - ${formatContainerDate(today)}`,
      '',
      'Share your quick sports takes! 280 characters of pure sports passion.',
      '',
      '---',
      `*Auto-generated by [Sportsblock](https://sportsblock.app) on ${dateStr}*`,
    ].join('\n');

    const metadata = JSON.stringify({
      app: `${SPORTS_ARENA_CONFIG.APP_NAME}/${SPORTS_ARENA_CONFIG.APP_VERSION}`,
      format: 'markdown',
      tags: ['sportsblock', 'sportsbites', SPORTSBITES_CONFIG.COMMUNITY_ID],
      community: SPORTSBITES_CONFIG.COMMUNITY_ID,
      content_type: 'sportsbites-container',
    });

    // Include comment_options to decline payout — the container is just a
    // wrapper; only the individual sportsbite replies should earn rewards.
    const result = await broadcastWithKey(
      [
        [
          'comment',
          {
            parent_author: '',
            parent_permlink: SPORTSBITES_CONFIG.COMMUNITY_ID,
            author: SPORTSBITES_CONFIG.PARENT_AUTHOR,
            permlink,
            title,
            body,
            json_metadata: metadata,
          },
        ],
        [
          'comment_options',
          {
            author: SPORTSBITES_CONFIG.PARENT_AUTHOR,
            permlink,
            max_accepted_payout: '0.000 HBD',
            percent_hbd: 10000,
            allow_votes: true,
            allow_curation_rewards: true,
            extensions: [],
          },
        ],
      ],
      postingKey
    );

    if (result.success) {
      createdContainers.add(permlink);
      console.log(`[EnsureContainer] Created container for ${dateStr}: tx=${result.transactionId}`);
      return NextResponse.json({
        success: true,
        permlink,
        created: true,
        transactionId: result.transactionId,
      });
    }

    // Hive returns errors like "You already have a comment with this permlink"
    // when the container already exists — treat as success.
    const isDuplicate =
      result.error &&
      (result.error.includes('already') ||
        result.error.includes('duplicate') ||
        result.error.includes('permlink'));

    if (isDuplicate) {
      createdContainers.add(permlink);
      console.log(`[EnsureContainer] Container already exists for ${dateStr}`);
      return NextResponse.json({
        success: true,
        permlink,
        alreadyExists: true,
      });
    }

    // Genuine failure
    throw new Error(result.error || 'Failed to create container');
  } catch (error) {
    return ctx.handleError(error);
  }
}
